version: '3.4'

networks:
  nginx-php81-mysql8:

services:

  # nginx
  blank-nginx-service:
    image: nginx:stable-alpine
    container_name: blank-nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blank-php81-service
      - blank-mysql8-service
    networks:
      - nginx-php81-mysql8

  # php
  blank-php81-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: blank-php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - nginx-php81-mysql8

 # mysql
  blank-mysql8-service:
    image: mysql:8
    container_name: blank-mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - nginx-php81-mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret