framework:
#    enabled_locales: [ 'en', 'pl' ]
    default_locale: en
#    set-locale-from-accept-language: true
#    set_content_language_from_locale: true
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
#            phrase:
#                dsn: '%env(PHRASE_DSN)%'
